### ISSUE TITLE
Transition into standalone operation

### ISSUE THREAD

**Issue by KDercksen** [KDercksen/cloogle-cli#4]
Since I want to support some different functionality that the Cloogle API doesn't offer yet, I'm thinking about implementing cloogle-cli as a standalone search tool. This is not yet a definitive decision, but I'm giving it some thought.

**Comment by camilstaps** [comment]
I'd strongly advise to do this in Clean, if you want to continue with this idea. Then you can use https://github.com/camilstaps/CleanTypeUnifier for type unification and parsing, and use Cloogle's builddb to build a type database using the Clean compiler's parser.

However, above that: we strongly welcome enhancement issues and pull requests on https://github.com/dopefishh/cloogle. The timing with your last PR was a bit unfortunate, because just the same day we finished an important part of type unification and wanted to merge that in asap.

**Comment by KDercksen** [comment]
Cloogle is coming along great, so I'm not choosing to implement standalone operation as of now.
